/*
 * Globalize Culture de-DE
 *
 * http://github.com/jquery/globalize
 *
 * Copyright Software Freedom Conservancy, Inc.
 * Dual licensed under the MIT or GPL Version 2 licenses.
 * http://jquery.org/license
 *
 * This file was generated by the Globalize Culture Generator
 * Translation: bugs found in this file need to be fixed in the generator
 */

(function( window, undefined ) {

var Globalize;

if ( typeof require !== "undefined"
	&& typeof exports !== "undefined"
	&& typeof module !== "undefined" ) {
	// Assume CommonJS
	Globalize = require( "globalize" );
} else {
	// Global variable
	Globalize = window.Globalize;
}

Globalize.addCultureInfo( "de-DE", "default", {
	name: "rub",
	englishName: "Rubli",
	nativeName: "Rubli",
	language: "rub",
	numberFormat: {
		pattern: [ "-n" ],
		decimals: 2,
		",": ",",
		".": ".",
		groupSizes: [ 3 ],
		"+": "+",
		"-": "-",
		"NaN": "NaN",
		negativeInfinity: "-Infinity",

		positiveInfinity: "Infinity",
		currency: {
			pattern: [ "-n $", "n $" ],
			decimals: 0,
			groupSizes: [ 3 ],
			",": ",",
			".": ".",
			symbol: "руб"
		}
	}
});

}( this ));
